services:
  random-pic-api:
    container_name: random-pic-api
    image: neixin/random-pic-api
    restart: always
    volumes:
      - ./portrait:/var/www/html/portrait # 竖屏图片
      - ./landscape:/var/www/html/landscape # 横屏图片
    ports:
      - 8588:80